export const LOCALES = ["en", "hi", "es", "fr", "pt-BR", "de", "ja", "ko"] as const;

export type Locale = (typeof LOCALES)[number];

export const LANGUAGE_NAMES: Record<Locale, string> = {
  en: "English",
  hi: "हिन्दी",
  es: "Español",
  fr: "Français",
  "pt-BR": "Português",
  de: "Deutsch",
  ja: "日本語",
  ko: "한국어",
};

const en = {
  tagline: "Draw it wrong. Guess it right.",
  eyebrow: "A tiny game for two people",
  description: "You get ten seconds to draw it. Send it to one person. They get exactly one guess.",
  heroEyebrow: "A tiny drawing dare for two",
  heroHook: "DRAW IT WRONG. MAKE THEM GUESS.",
  heroSubhead: "Get a secret prompt. Draw it in 10 seconds: recognizable, not pretty. Send the replay. Your friend gets one guess, then draws one back.",
  makeChallenge: "Give me a prompt",
  dailyDisaster: "Play today's prompt",
  dailyMeta: "Same prompt for everyone. New one every day.",
  dailyStreak: "{n}-day streak",
  howTitle: "One bad drawing starts a chain",
  howSubtitle: "Draw → send → guess → draw one back.",
  stepPromptTitle: "Get a secret prompt",
  stepPromptBody: "You get one thing to draw. No choosing the easy one.",
  stepDrawTitle: "Draw badly for 10 seconds",
  stepDrawBody: "Your timer starts on the first stroke. Recognizable beats pretty.",
  stepSendTitle: "Send it. They get one guess.",
  stepSendBody: "The replay runs once. Pick the answer before it gives itself away.",
  dailyShareText: "Today's disaster: same prompt for everyone. I had 10 seconds. Can you guess it?",
  groupShareText: "Group test: who can identify this 10-second disaster first? One replay. One guess.",
  dailyChallengeLabel: "Today's Disaster, {date}",
  drawToday: "Draw today's disaster",
  dailyComplete: "Today's disaster survived.",
  shareResultCorrect: "I guessed this 10-second disaster in {n}s. Beat my time:",
  shareResultWrong: "This 10-second disaster fooled me. Can you get it in one guess?",
  makeGroupGuess: "Make the group guess",
  randomMode: "Random challenge",
  oneGuess: "10 sec · 1 guess",
  drawSomething: "Draw something",
  privacyLine: "Free. No app. No account. Just one link.",
  forBrave: "For someone brave",
  canTheyTell: "can they tell?",
  oneGuessNoMercy: "one guess. no mercy.",
  quit: "quit",
  yourPrompt: "Your prompt",
  makeRecognizable: "Make it recognizable. Beauty is disqualifying.",
  timerStarts: "The timer starts with your first line.",
  seconds: "{n}s",
  clear: "Clear",
  finish: "Finish drawing",
  drawAnywhere: "draw here",
  noDrawing: "No drawing? Bold move.",
  challengeReady: "Challenge ready!",
  drawingSafe: "Short links expire after 30 days. Shared drawings are stored temporarily so those links work. Anyone with the link can replay them. Don’t draw secrets.",
  shareTitle: "Send your disaster",
  shareBody: "Challenge one friend, or drop it in a group and see who recognizes it first.",
  shareChallenge: "Send the challenge",
  copyLink: "Copy link",
  linkCopied: "Link copied!",
  makingShortLink: "Making a short link…",
  shortLinkFallback: "Short-link service is unavailable, so the longer backup link was copied.",
  someoneDrew: "Someone drew this…",
  guessBeforeFinish: "What did they try to draw?",
  startGuessing: "Start the replay",
  yourGuess: "Your guess",
  replay: "Replay",
  correct: "Correct!",
  wrong: "Not quite!",
  tooSlow: "Too slow!",
  timeTaken: "Time taken",
  itWas: "It was {answer}.",
  recognitionTime: "Recognition time",
  drawOneBack: "Draw one back",
  challengeSomeoneElse: "Challenge someone else",
  dropInGroup: "Drop it in a group",
  tryAnother: "Try another prompt",
  simplified: "We lightly simplified the line so the link stays shareable.",
  invalidLink: "This drawing got smudged.",
  invalidBody: "The challenge link is incomplete or from a newer version.",
  goHome: "Make a new challenge",
  language: "Language",
  shareText: "I had 10 seconds to draw this. Tap when you know what it is. One guess:",
  shareBackText: "I drew one back for you. One guess:",
  tapToGuess: "Tap as soon as you know. You get one guess.",
  waiting: "The ink is about to move…",
  guessedIn: "Guessed in {n}s",
  drawingLimit: "That is enough chaos. Finish and share it.",
} as const;

export type UiKey = keyof typeof en;

export const UI: Record<Locale, Record<UiKey, string>> = {
  en,
  hi: {
    tagline: "गलत बनाओ, सही पहचानो!",
    eyebrow: "दो लोगों के लिए एक छोटा खेल",
    description: "बनाने के लिए दस सेकंड। किसी एक को भेजो। उन्हें सिर्फ़ एक मौका मिलेगा।",
    heroEyebrow: "दो लोगों के लिए एक छोटा-सा ड्रॉइंग डेयर",
    heroHook: "गलत बनाओ। उनसे पहचानवाओ।",
    heroSubhead: "एक गुप्त चीज़ पाओ। उसे 10 सेकंड में बनाओ: सुंदर नहीं, बस पहचानने लायक। रीप्ले भेजो। तुम्हारे दोस्त को सिर्फ़ एक जवाब मिलेगा, फिर वह भी एक बनाकर वापस भेजेगा।",
    makeChallenge: "मुझे एक शब्द दो",
    dailyDisaster: "आज का शब्द बनाओ",
    dailyMeta: "सबके लिए वही चीज़। हर दिन नई।",
    dailyStreak: "{n} दिन की स्ट्रीक",
    howTitle: "एक खराब ड्रॉइंग से सिलसिला शुरू होता है",
    howSubtitle: "बनाओ → भेजो → पहचानो → एक वापस बनाओ।",
    stepPromptTitle: "गुप्त चीज़ पाओ",
    stepPromptBody: "बनाने के लिए एक चीज़ मिलेगी। आसान वाली चुनने का मौका नहीं।",
    stepDrawTitle: "10 सेकंड तक बुरी ड्रॉइंग बनाओ",
    stepDrawBody: "पहली लाइन के साथ टाइमर शुरू होगा। सुंदर नहीं, पहचानने लायक बनाओ।",
    stepSendTitle: "भेजो। उन्हें एक जवाब मिलेगा।",
    stepSendBody: "रीप्ले सिर्फ़ एक बार चलेगा। जवाब खुद दिख जाए, उससे पहले चुनो।",
    dailyShareText: "आज की तबाही: सबके लिए वही चीज़। मेरे पास 10 सेकंड थे। क्या तुम पहचान सकते हो?",
    groupShareText: "ग्रुप टेस्ट: इस 10 सेकंड की तबाही को सबसे पहले कौन पहचानेगा? एक रीप्ले। एक जवाब।",
    dailyChallengeLabel: "आज की तबाही, {date}",
    drawToday: "आज की तबाही बनाओ",
    dailyComplete: "आज की तबाही बच गई।",
    shareResultCorrect: "मैंने इस 10 सेकंड की तबाही को {n}s में पहचान लिया। मेरा समय हराओ:",
    shareResultWrong: "इस 10 सेकंड की तबाही ने मुझे बेवकूफ बना दिया। क्या तुम एक जवाब में पहचान लोगे?",
    makeGroupGuess: "ग्रुप से पहचानने को कहो",
    randomMode: "रैंडम चैलेंज",
    oneGuess: "10 सेकंड · 1 जवाब",
    drawSomething: "कुछ बनाओ",
    privacyLine: "मुफ्त। न ऐप। न अकाउंट। बस एक लिंक।",
    forBrave: "किसी बहादुर के लिए",
    canTheyTell: "क्या वे पहचानेंगे?",
    oneGuessNoMercy: "एक जवाब। कोई रहम नहीं।",
    quit: "छोड़ें",
    yourPrompt: "तुम्हारा शब्द",
    makeRecognizable: "पहचान में आए ऐसा बनाओ। बहुत सुंदर बनाया तो अयोग्य!",
    timerStarts: "पहली लाइन के साथ टाइमर शुरू होगा।",
    seconds: "{n} सेकंड",
    clear: "साफ़ करें",
    finish: "पूरा हुआ",
    drawAnywhere: "यहाँ बनाओ",
    noDrawing: "कुछ नहीं बनाया? बड़ी हिम्मत है।",
    challengeReady: "चैलेंज तैयार है!",
    drawingSafe: "शॉर्ट लिंक 30 दिनों बाद एक्सपायर हो जाते हैं। उनके लिए शेयर की गई ड्रॉइंग अस्थायी रूप से रखी जाती हैं। जिसके पास लिंक है, वह उन्हें रीप्ले कर सकता है। कोई राज़ मत बनाओ।",
    shareTitle: "अपनी तबाही भेजो",
    shareBody: "एक दोस्त को चैलेंज करो, या ग्रुप में डालो और देखो सबसे पहले कौन पहचानता है।",
    shareChallenge: "चैलेंज भेजो",
    copyLink: "लिंक कॉपी करें",
    linkCopied: "लिंक कॉपी हो गया!",
    makingShortLink: "छोटा लिंक बन रहा है…",
    shortLinkFallback: "शॉर्ट लिंक सेवा अभी उपलब्ध नहीं है, इसलिए लंबा बैकअप लिंक कॉपी किया गया है।",
    someoneDrew: "किसी ने यह बनाया है…",
    guessBeforeFinish: "उन्होंने क्या बनाने की कोशिश की?",
    startGuessing: "रीप्ले शुरू करो",
    yourGuess: "तुम्हारा जवाब",
    replay: "फिर से देखें",
    correct: "सही!",
    wrong: "थोड़ा चूके!",
    tooSlow: "समय खत्म!",
    timeTaken: "लगा समय",
    itWas: "सही जवाब था: {answer}।",
    recognitionTime: "पहचानने का समय",
    drawOneBack: "एक वापस बनाओ",
    challengeSomeoneElse: "किसी और को चैलेंज करो",
    dropInGroup: "ग्रुप में भेजो",
    tryAnother: "दूसरा शब्द",
    simplified: "लिंक छोटा रखने के लिए लाइन थोड़ी सरल की गई।",
    invalidLink: "यह चित्र धुँधला गया।",
    invalidBody: "चैलेंज लिंक अधूरा है या किसी नए वर्ज़न का है।",
    goHome: "नया चैलेंज बनाओ",
    language: "भाषा",
    shareText: "मेरे पास इसे बनाने के लिए 10 सेकंड थे। समझ आते ही टैप करो। सिर्फ़ एक जवाब:",
    shareBackText: "मैंने तुम्हारे लिए एक वापस बनाया। सिर्फ़ एक जवाब:",
    tapToGuess: "पता चलते ही टैप करो। तुम्हें सिर्फ़ एक जवाब मिलेगा।",
    waiting: "स्याही चलने वाली है…",
    guessedIn: "{n} सेकंड में पहचाना",
    drawingLimit: "इतनी अफ़रा-तफ़री काफ़ी है। अब इसे भेजो।",
  },
  es: {
    tagline: "Dibújalo mal. Aciértalo bien.",
    eyebrow: "Un minijuego para dos",
    description: "Tienes diez segundos para dibujarlo. Envíalo a una persona. Solo tendrá un intento.",
    heroEyebrow: "Un minirreto de dibujo para dos",
    heroHook: "DIBÚJALO MAL. QUE LO ADIVINE.",
    heroSubhead: "Recibe una palabra secreta. Dibújala en 10 segundos: que se reconozca, no que quede bonita. Envía la repetición. La otra persona tiene un intento y luego te manda otro dibujo.",
    makeChallenge: "Dame una palabra",
    dailyDisaster: "Dibujar la palabra de hoy",
    dailyMeta: "La misma palabra para todos. Una nueva cada día.",
    dailyStreak: "Racha de {n} días",
    howTitle: "Un mal dibujo inicia una cadena",
    howSubtitle: "Dibuja → envía → adivina → devuelve otro dibujo.",
    stepPromptTitle: "Recibe una palabra secreta",
    stepPromptBody: "Te toca dibujar una cosa. No puedes elegir la fácil.",
    stepDrawTitle: "Dibuja mal durante 10 segundos",
    stepDrawBody: "El tiempo empieza con el primer trazo. Mejor reconocible que bonito.",
    stepSendTitle: "Envíalo. Tiene un intento.",
    stepSendBody: "La repetición se reproduce una vez. Elige antes de que revele la respuesta.",
    dailyShareText: "El desastre de hoy: la misma palabra para todos. Tuve 10 segundos. ¿Puedes adivinarlo?",
    groupShareText: "Prueba de grupo: ¿quién identifica primero este desastre de 10 segundos? Una repetición. Un intento.",
    dailyChallengeLabel: "El desastre de hoy, {date}",
    drawToday: "Dibuja el desastre de hoy",
    dailyComplete: "El desastre de hoy sobrevivió.",
    shareResultCorrect: "Adiviné este desastre de 10 segundos en {n}s. Supera mi tiempo:",
    shareResultWrong: "Este desastre de 10 segundos me engañó. ¿Lo consigues con un intento?",
    makeGroupGuess: "Haz que el grupo adivine",
    randomMode: "Reto aleatorio",
    oneGuess: "10 s · 1 intento",
    drawSomething: "Dibuja algo",
    privacyLine: "Gratis. Sin app. Sin cuenta. Solo un enlace.",
    forBrave: "Para alguien valiente",
    canTheyTell: "¿lo reconocerá?",
    oneGuessNoMercy: "un intento. sin piedad.",
    quit: "salir",
    yourPrompt: "Tu palabra",
    makeRecognizable: "Hazlo reconocible. Si queda bonito, pierdes.",
    timerStarts: "El tiempo empieza con tu primera línea.",
    seconds: "{n} s",
    clear: "Borrar",
    finish: "Terminar dibujo",
    drawAnywhere: "dibuja aquí",
    noDrawing: "¿No dibujaste? Qué valiente.",
    challengeReady: "¡Reto listo!",
    drawingSafe: "Los enlaces cortos caducan a los 30 días. Los dibujos compartidos se guardan temporalmente para que esos enlaces funcionen. Cualquiera con el enlace puede reproducirlos. No dibujes secretos.",
    shareTitle: "Envía tu desastre",
    shareBody: "Reta a una persona, o mándalo a un grupo y mira quién lo reconoce primero.",
    shareChallenge: "Enviar el reto",
    copyLink: "Copiar enlace",
    linkCopied: "¡Enlace copiado!",
    makingShortLink: "Creando un enlace corto…",
    shortLinkFallback: "El servicio de enlaces cortos no está disponible, así que se copió el enlace de respaldo más largo.",
    someoneDrew: "Alguien dibujó esto…",
    guessBeforeFinish: "¿Qué intentó dibujar?",
    startGuessing: "Iniciar la repetición",
    yourGuess: "Tu respuesta",
    replay: "Repetir",
    correct: "¡Correcto!",
    wrong: "¡Casi!",
    tooSlow: "¡Demasiado tarde!",
    timeTaken: "Tiempo empleado",
    itWas: "Era {answer}.",
    recognitionTime: "Tiempo para reconocerlo",
    drawOneBack: "Dibuja uno de vuelta",
    challengeSomeoneElse: "Reta a otra persona",
    dropInGroup: "Envíalo a un grupo",
    tryAnother: "Otra palabra",
    simplified: "Simplificamos un poco la línea para mantener corto el enlace.",
    invalidLink: "Este dibujo se borró.",
    invalidBody: "El enlace está incompleto o viene de una versión nueva.",
    goHome: "Crear un reto nuevo",
    language: "Idioma",
    shareText: "Tuve 10 segundos para dibujar esto. Toca cuando sepas qué es. Un intento:",
    shareBackText: "Te dibujé uno de vuelta. Un solo intento:",
    tapToGuess: "Toca en cuanto lo sepas. Solo tienes un intento.",
    waiting: "La tinta está a punto de moverse…",
    guessedIn: "Adivinado en {n} s",
    drawingLimit: "Ya hay suficiente caos. Termina y compártelo.",
  },
  fr: {
    tagline: "Dessine mal. Devine juste.",
    eyebrow: "Un mini-jeu pour deux",
    description: "Tu as dix secondes pour dessiner. Envoie-le à une personne. Elle n’aura qu’une réponse.",
    heroEyebrow: "Un mini-défi de dessin à deux",
    heroHook: "DESSINE-LE MAL. FAIS-LE DEVINER.",
    heroSubhead: "Reçois un mot secret. Dessine-le en 10 secondes : reconnaissable, pas joli. Envoie le replay. L’autre personne n’a droit qu’à une réponse, puis te renvoie un dessin.",
    makeChallenge: "Donne-moi un mot",
    dailyDisaster: "Dessiner le mot du jour",
    dailyMeta: "Le même mot pour tout le monde. Un nouveau chaque jour.",
    dailyStreak: "Série de {n} jours",
    howTitle: "Un dessin raté lance une chaîne",
    howSubtitle: "Dessine → envoie → devine → dessine en retour.",
    stepPromptTitle: "Reçois un mot secret",
    stepPromptBody: "Tu as une chose à dessiner. Pas le droit de choisir la plus facile.",
    stepDrawTitle: "Dessine mal pendant 10 secondes",
    stepDrawBody: "Le chrono démarre au premier trait. Reconnaissable vaut mieux que joli.",
    stepSendTitle: "Envoie-le. Une seule réponse.",
    stepSendBody: "Le replay passe une fois. Choisis avant qu'il ne donne la réponse.",
    dailyShareText: "Le désastre du jour : le même mot pour tout le monde. J'avais 10 secondes. Tu devines ?",
    groupShareText: "Test de groupe : qui reconnaîtra ce désastre de 10 secondes en premier ? Un replay. Une réponse.",
    dailyChallengeLabel: "Le désastre du jour, {date}",
    drawToday: "Dessiner le désastre du jour",
    dailyComplete: "Le désastre du jour a survécu.",
    shareResultCorrect: "J'ai deviné ce désastre de 10 secondes en {n}s. Bats mon temps :",
    shareResultWrong: "Ce désastre de 10 secondes m'a eu. Tu y arrives avec une réponse ?",
    makeGroupGuess: "Faire deviner le groupe",
    randomMode: "Défi aléatoire",
    oneGuess: "10 s · 1 réponse",
    drawSomething: "Dessiner quelque chose",
    privacyLine: "Gratuit. Sans appli. Sans compte. Juste un lien.",
    forBrave: "Pour quelqu’un de courageux",
    canTheyTell: "va-t-on deviner ?",
    oneGuessNoMercy: "une réponse. aucune pitié.",
    quit: "quitter",
    yourPrompt: "Ton mot",
    makeRecognizable: "Il faut qu’on reconnaisse. Trop beau = disqualifié.",
    timerStarts: "Le chrono démarre au premier trait.",
    seconds: "{n} s",
    clear: "Effacer",
    finish: "Terminer le dessin",
    drawAnywhere: "dessine ici",
    noDrawing: "Pas de dessin ? Audacieux.",
    challengeReady: "Défi prêt !",
    drawingSafe: "Les liens courts expirent après 30 jours. Les dessins partagés sont conservés temporairement pour que ces liens fonctionnent. Toute personne ayant le lien peut les revoir. Ne dessine rien de secret.",
    shareTitle: "Envoie ton désastre",
    shareBody: "Défie une personne, ou envoie-le dans un groupe pour voir qui le reconnaît en premier.",
    shareChallenge: "Envoyer le défi",
    copyLink: "Copier le lien",
    linkCopied: "Lien copié !",
    makingShortLink: "Création d’un lien court…",
    shortLinkFallback: "Le service de liens courts est indisponible, donc le lien de secours plus long a été copié.",
    someoneDrew: "Quelqu’un a dessiné ça…",
    guessBeforeFinish: "Qu’est-ce qu’on a essayé de dessiner ?",
    startGuessing: "Lancer le replay",
    yourGuess: "Ta réponse",
    replay: "Revoir",
    correct: "Correct !",
    wrong: "Pas tout à fait !",
    tooSlow: "Trop tard !",
    timeTaken: "Temps écoulé",
    itWas: "C’était {answer}.",
    recognitionTime: "Temps de reconnaissance",
    drawOneBack: "Dessiner en retour",
    challengeSomeoneElse: "Défier quelqu’un d’autre",
    dropInGroup: "L’envoyer dans un groupe",
    tryAnother: "Un autre mot",
    simplified: "Le trait a été un peu simplifié pour garder un lien court.",
    invalidLink: "Ce dessin s’est effacé.",
    invalidBody: "Le lien est incomplet ou vient d’une version plus récente.",
    goHome: "Créer un nouveau défi",
    language: "Langue",
    shareText: "J’avais 10 secondes pour dessiner ça. Appuie dès que tu sais ce que c’est. Une seule réponse :",
    shareBackText: "Je t’en ai dessiné un en retour. Une seule réponse :",
    tapToGuess: "Appuie dès que tu sais. Tu n’as droit qu’à une réponse.",
    waiting: "L’encre va se mettre à bouger…",
    guessedIn: "Deviné en {n} s",
    drawingLimit: "Assez de chaos : termine et partage.",
  },
  "pt-BR": {
    tagline: "Desenhe errado. Acerte na resposta.",
    eyebrow: "Um joguinho para duas pessoas",
    description: "Você tem dez segundos para desenhar. Envie para uma pessoa. Ela só pode dar um palpite.",
    heroEyebrow: "Um mini desafio de desenho para dois",
    heroHook: "DESENHE ERRADO. FAÇA ALGUÉM ADIVINHAR.",
    heroSubhead: "Receba uma palavra secreta. Faça o desenho em 10 segundos: reconhecível, não bonito. Envie o replay. A outra pessoa tem um palpite e depois manda outro desenho de volta.",
    makeChallenge: "Me dê uma palavra",
    dailyDisaster: "Desenhar a palavra de hoje",
    dailyMeta: "A mesma palavra para todo mundo. Uma nova por dia.",
    dailyStreak: "Sequência de {n} dias",
    howTitle: "Um desenho ruim começa uma corrente",
    howSubtitle: "Desenhe → envie → adivinhe → desenhe outro de volta.",
    stepPromptTitle: "Receba uma palavra secreta",
    stepPromptBody: "Você recebe uma coisa para desenhar. Nada de escolher a fácil.",
    stepDrawTitle: "Desenhe mal por 10 segundos",
    stepDrawBody: "O tempo começa no primeiro traço. Reconhecível ganha de bonito.",
    stepSendTitle: "Envie. A pessoa tem um palpite.",
    stepSendBody: "O replay roda uma vez. Escolha antes que ele entregue a resposta.",
    dailyShareText: "O desastre de hoje: a mesma palavra para todo mundo. Eu tive 10 segundos. Você adivinha?",
    groupShareText: "Teste do grupo: quem identifica primeiro este desastre de 10 segundos? Um replay. Um palpite.",
    dailyChallengeLabel: "O desastre de hoje, {date}",
    drawToday: "Desenhar o desastre de hoje",
    dailyComplete: "O desastre de hoje sobreviveu.",
    shareResultCorrect: "Adivinhei este desastre de 10 segundos em {n}s. Bata meu tempo:",
    shareResultWrong: "Este desastre de 10 segundos me enganou. Você acerta com um palpite?",
    makeGroupGuess: "Faça o grupo adivinhar",
    randomMode: "Desafio aleatório",
    oneGuess: "10 s · 1 palpite",
    drawSomething: "Desenhe algo",
    privacyLine: "Grátis. Sem app. Sem conta. Só um link.",
    forBrave: "Para alguém corajoso",
    canTheyTell: "será que acerta?",
    oneGuessNoMercy: "um palpite. sem dó.",
    quit: "sair",
    yourPrompt: "Sua palavra",
    makeRecognizable: "Faça dar para reconhecer. Bonito demais está eliminado.",
    timerStarts: "O tempo começa no primeiro traço.",
    seconds: "{n} s",
    clear: "Limpar",
    finish: "Terminar desenho",
    drawAnywhere: "desenhe aqui",
    noDrawing: "Não desenhou? Ousado.",
    challengeReady: "Desafio pronto!",
    drawingSafe: "Os links curtos expiram após 30 dias. Os desenhos compartilhados ficam armazenados temporariamente para que esses links funcionem. Qualquer pessoa com o link pode revê-los. Não desenhe nada secreto.",
    shareTitle: "Envie seu desastre",
    shareBody: "Desafie uma pessoa, ou mande no grupo e veja quem reconhece primeiro.",
    shareChallenge: "Enviar o desafio",
    copyLink: "Copiar link",
    linkCopied: "Link copiado!",
    makingShortLink: "Criando um link curto…",
    shortLinkFallback: "O serviço de links curtos está indisponível, então foi copiado o link alternativo mais longo.",
    someoneDrew: "Alguém desenhou isto…",
    guessBeforeFinish: "O que essa pessoa tentou desenhar?",
    startGuessing: "Iniciar o replay",
    yourGuess: "Seu palpite",
    replay: "Rever",
    correct: "Acertou!",
    wrong: "Quase!",
    tooSlow: "Tempo esgotado!",
    timeTaken: "Tempo levado",
    itWas: "Era {answer}.",
    recognitionTime: "Tempo para reconhecer",
    drawOneBack: "Desenhe um de volta",
    challengeSomeoneElse: "Desafie outra pessoa",
    dropInGroup: "Mande no grupo",
    tryAnother: "Outra palavra",
    simplified: "Simplificamos um pouco o traço para manter o link curto.",
    invalidLink: "Este desenho borrou.",
    invalidBody: "O link está incompleto ou veio de uma versão mais nova.",
    goHome: "Criar um novo desafio",
    language: "Idioma",
    shareText: "Tive 10 segundos para desenhar isso. Toque assim que souber o que é. Um palpite só:",
    shareBackText: "Desenhei um de volta para você. Um palpite:",
    tapToGuess: "Toque assim que souber. Você só tem um palpite.",
    waiting: "A tinta vai começar a se mexer…",
    guessedIn: "Adivinhou em {n} s",
    drawingLimit: "Já deu de caos. Termine e compartilhe.",
  },
  de: {
    tagline: "Falsch zeichnen. Richtig raten.",
    eyebrow: "Ein winziges Spiel für zwei",
    description: "Du hast zehn Sekunden zum Zeichnen. Schick es einer Person. Sie hat genau einen Versuch.",
    heroEyebrow: "Eine kleine Zeichen-Challenge zu zweit",
    heroHook: "ZEICHNE FALSCH. LASS SIE RATEN.",
    heroSubhead: "Hol dir einen geheimen Begriff. Zeichne ihn in 10 Sekunden: erkennbar, nicht hübsch. Schick das Replay. Dein Gegenüber hat einen Versuch und zeichnet dir danach etwas zurück.",
    makeChallenge: "Gib mir einen Begriff",
    dailyDisaster: "Heutigen Begriff zeichnen",
    dailyMeta: "Derselbe Begriff für alle. Jeden Tag ein neuer.",
    dailyStreak: "{n}-Tage-Serie",
    howTitle: "Mit einer miesen Zeichnung beginnt die Kette",
    howSubtitle: "Zeichnen → schicken → raten → zurückzeichnen.",
    stepPromptTitle: "Hol dir einen geheimen Begriff",
    stepPromptBody: "Du bekommst eine Sache zum Zeichnen. Die einfache darfst du nicht wählen.",
    stepDrawTitle: "10 Sekunden schlecht zeichnen",
    stepDrawBody: "Die Zeit startet mit dem ersten Strich. Erkennbar schlägt hübsch.",
    stepSendTitle: "Schick es ab. Eine Antwort.",
    stepSendBody: "Das Replay läuft einmal. Wähle, bevor es die Antwort verrät.",
    dailyShareText: "Das Desaster des Tages: derselbe Begriff für alle. Ich hatte 10 Sekunden. Kannst du es erraten?",
    groupShareText: "Gruppentest: Wer erkennt dieses 10-Sekunden-Desaster zuerst? Ein Replay. Eine Antwort.",
    dailyChallengeLabel: "Das Desaster des Tages, {date}",
    drawToday: "Das Desaster des Tages zeichnen",
    dailyComplete: "Das Desaster des Tages hat überlebt.",
    shareResultCorrect: "Ich habe dieses 10-Sekunden-Desaster in {n}s erraten. Schlägst du meine Zeit?",
    shareResultWrong: "Dieses 10-Sekunden-Desaster hat mich erwischt. Schaffst du es mit einer Antwort?",
    makeGroupGuess: "Lass die Gruppe raten",
    randomMode: "Zufallschallenge",
    oneGuess: "10 Sek. · 1 Versuch",
    drawSomething: "Etwas zeichnen",
    privacyLine: "Kostenlos. Keine App. Kein Konto. Nur ein Link.",
    forBrave: "Für einen mutigen Menschen",
    canTheyTell: "wird es erkannt?",
    oneGuessNoMercy: "ein Versuch. keine Gnade.",
    quit: "beenden",
    yourPrompt: "Dein Begriff",
    makeRecognizable: "Erkennbar muss es sein. Zu schön ist disqualifiziert.",
    timerStarts: "Die Zeit startet mit deinem ersten Strich.",
    seconds: "{n} Sek.",
    clear: "Löschen",
    finish: "Zeichnung beenden",
    drawAnywhere: "hier zeichnen",
    noDrawing: "Nichts gezeichnet? Mutig.",
    challengeReady: "Herausforderung bereit!",
    drawingSafe: "Kurzlinks laufen nach 30 Tagen ab. Geteilte Zeichnungen werden vorübergehend gespeichert, damit diese Links funktionieren. Jeder mit dem Link kann sie abspielen. Zeichne nichts Geheimes.",
    shareTitle: "Schick dein Desaster",
    shareBody: "Fordere eine Person heraus oder schick es in eine Gruppe und schau, wer es zuerst erkennt.",
    shareChallenge: "Challenge senden",
    copyLink: "Link kopieren",
    linkCopied: "Link kopiert!",
    makingShortLink: "Kurzlink wird erstellt …",
    shortLinkFallback: "Der Kurzlink-Dienst ist nicht verfügbar. Deshalb wurde der längere Ersatzlink kopiert.",
    someoneDrew: "Jemand hat das gezeichnet …",
    guessBeforeFinish: "Was sollte das werden?",
    startGuessing: "Replay starten",
    yourGuess: "Dein Tipp",
    replay: "Wiederholen",
    correct: "Richtig!",
    wrong: "Knapp daneben!",
    tooSlow: "Zu spät!",
    timeTaken: "Benötigte Zeit",
    itWas: "Es war {answer}.",
    recognitionTime: "Ratezeit",
    drawOneBack: "Etwas zurückzeichnen",
    challengeSomeoneElse: "Jemand anderen herausfordern",
    dropInGroup: "In eine Gruppe schicken",
    tryAnother: "Anderer Begriff",
    simplified: "Der Strich wurde leicht vereinfacht, damit der Link kurz bleibt.",
    invalidLink: "Diese Zeichnung ist verwischt.",
    invalidBody: "Der Link ist unvollständig oder aus einer neueren Version.",
    goHome: "Neue Herausforderung erstellen",
    language: "Sprache",
    shareText: "Ich hatte 10 Sekunden, um das zu zeichnen. Tippe, sobald du weißt, was es ist. Ein Versuch:",
    shareBackText: "Ich habe dir eins zurückgezeichnet. Ein Versuch:",
    tapToGuess: "Tippe, sobald du es weißt. Du hast nur einen Versuch.",
    waiting: "Gleich bewegt sich die Tinte …",
    guessedIn: "In {n} Sek. erkannt",
    drawingLimit: "Genug Chaos. Fertigstellen und teilen.",
  },
  ja: {
    tagline: "ヘタに描いて、当てよう。",
    eyebrow: "ふたりで遊ぶミニゲーム",
    description: "10秒で描いて、ひとりに送ろう。答えられるのは一度だけ。",
    heroEyebrow: "ふたりで遊ぶ、ちいさなお絵描きチャレンジ",
    heroHook: "ヘタに描こう。相手に当てさせよう。",
    heroSubhead: "ひみつのお題をもらったら、10秒で描こう。きれいじゃなくていい、伝わればOK。リプレイを送ると、相手の回答は1回だけ。そのあと相手が描き返す。",
    makeChallenge: "お題をちょうだい",
    dailyDisaster: "今日のお題で遊ぶ",
    dailyMeta: "お題は全員同じ。毎日新しい。",
    dailyStreak: "{n}日連続",
    howTitle: "1枚のヘタ絵が、次のヘタ絵を呼ぶ",
    howSubtitle: "描く → 送る → 当てる → 描き返す。",
    stepPromptTitle: "ひみつのお題を受け取る",
    stepPromptBody: "描くものは1つ。簡単なほうを選ぶのはなし。",
    stepDrawTitle: "10秒でヘタに描く",
    stepDrawBody: "最初の線でタイマー開始。きれいさより伝わること。",
    stepSendTitle: "送る。相手の回答は1回。",
    stepSendBody: "リプレイは1回だけ。答えがバレる前に選ぼう。",
    dailyShareText: "今日の大惨事: お題は全員同じ。私にあったのは10秒。これ、当てられる？",
    groupShareText: "グループテスト: この10秒の大惨事を最初に当てるのは誰？ リプレイ1回。回答1回。",
    dailyChallengeLabel: "今日の大惨事, {date}",
    drawToday: "今日の大惨事を描く",
    dailyComplete: "今日の大惨事は生き延びた。",
    shareResultCorrect: "この10秒の大惨事を{n}秒で当てた。私のタイムを超えられる？",
    shareResultWrong: "この10秒の大惨事にやられた。1回の回答で当てられる？",
    makeGroupGuess: "グループに当てさせる",
    randomMode: "ランダムチャレンジ",
    oneGuess: "10秒 · 1回答",
    drawSomething: "お題を描こう",
    privacyLine: "無料。アプリ不要。アカウント不要。リンクひとつだけ。",
    forBrave: "勇気ある誰かへ",
    canTheyTell: "わかるかな？",
    oneGuessNoMercy: "一度だけ。容赦なし。",
    quit: "やめる",
    yourPrompt: "お題",
    makeRecognizable: "わかるように描こう。うますぎたら失格。",
    timerStarts: "最初の線でタイマーが始まります。",
    seconds: "{n}秒",
    clear: "消す",
    finish: "描き終える",
    drawAnywhere: "ここに描こう",
    noDrawing: "描かないの？大胆だね。",
    challengeReady: "チャレンジ完成！",
    drawingSafe: "短いリンクは30日後に期限切れになります。短いリンクが使えるよう、共有した絵は一時的に保存されます。リンクを知っている人なら誰でもリプレイできます。秘密は描かないで。",
    shareTitle: "この大惨事を送ろう",
    shareBody: "友だち1人に挑戦状を送ろう。グループに投げて、誰が最初に当てるか試すのもアリ。",
    shareChallenge: "チャレンジを送る",
    copyLink: "リンクをコピー",
    linkCopied: "リンクをコピーした！",
    makingShortLink: "短いリンクを作成中…",
    shortLinkFallback: "短縮リンクサービスを利用できないため、代わりに長い予備リンクをコピーしました。",
    someoneDrew: "誰かがこれを描いた…",
    guessBeforeFinish: "何を描こうとしたの？",
    startGuessing: "リプレイを始める",
    yourGuess: "あなたの答え",
    replay: "リプレイ",
    correct: "正解！",
    wrong: "おしい！",
    tooSlow: "時間切れ！",
    timeTaken: "かかった時間",
    itWas: "答えは「{answer}」でした。",
    recognitionTime: "当てる時間",
    drawOneBack: "描き返そう",
    challengeSomeoneElse: "別の人にも挑戦状！",
    dropInGroup: "グループに送る",
    tryAnother: "別のお題",
    simplified: "リンクを短くするため、線を少しだけ簡略化しました。",
    invalidLink: "絵がにじんでしまった。",
    invalidBody: "リンクが不完全か、新しいバージョンのものです。",
    goHome: "新しいチャレンジを作る",
    language: "言語",
    shareText: "これ、10秒で描いた。何かわかった瞬間にタップして。答えは1回だけ：",
    shareBackText: "描き返したよ。一度で当てて：",
    tapToGuess: "わかった瞬間にタップ。答えられるのは1回だけ。",
    waiting: "もうすぐインクが動き出す…",
    guessedIn: "{n}秒で正解",
    drawingLimit: "もう十分カオス。完成して送ろう。",
  },
  ko: {
    tagline: "엉망으로 그리고, 맞혀봐!",
    eyebrow: "둘이서 하는 초미니 게임",
    description: "10초 안에 그리고 한 명에게 보내세요. 답은 딱 한 번만 고를 수 있어요.",
    heroEyebrow: "둘이서 하는 초미니 그림 챌린지",
    heroHook: "엉망으로 그려. 상대가 맞히게 해.",
    heroSubhead: "비밀 제시어를 받아 10초 안에 그려요. 예쁘게 말고, 알아볼 수 있게. 리플레이를 보내면 친구에게는 한 번의 기회만 있어요. 그다음엔 친구가 하나 그려서 돌려줘요.",
    makeChallenge: "제시어 줘",
    dailyDisaster: "오늘의 제시어 도전하기",
    dailyMeta: "모두 같은 제시어. 매일 새로 바뀌어요.",
    dailyStreak: "{n}일 연속",
    howTitle: "못 그린 그림 하나가 그림 릴레이를 시작해요",
    howSubtitle: "그리기 → 보내기 → 맞히기 → 하나 그려 보내기.",
    stepPromptTitle: "비밀 제시어 받기",
    stepPromptBody: "그릴 것은 하나예요. 쉬운 걸 고를 수는 없어요.",
    stepDrawTitle: "10초 동안 못 그리기",
    stepDrawBody: "첫 선을 긋는 순간 타이머가 시작돼요. 예쁨보다 알아보기 쉬운 게 우선.",
    stepSendTitle: "보내세요. 기회는 한 번.",
    stepSendBody: "리플레이는 한 번만 재생돼요. 답이 들키기 전에 고르세요.",
    dailyShareText: "오늘의 참사: 모두 같은 제시어. 내겐 10초가 있었어. 이거 맞힐 수 있어?",
    groupShareText: "그룹 테스트: 이 10초짜리 참사를 가장 먼저 알아보는 사람은 누구? 리플레이 한 번. 기회 한 번.",
    dailyChallengeLabel: "오늘의 참사, {date}",
    drawToday: "오늘의 참사 그리기",
    dailyComplete: "오늘의 참사가 살아남았어요.",
    shareResultCorrect: "이 10초짜리 참사를 {n}초 만에 맞혔어. 내 기록을 깨봐:",
    shareResultWrong: "이 10초짜리 참사에 속았어. 한 번의 기회로 맞힐 수 있어?",
    makeGroupGuess: "그룹에게 맞혀 보라고 하기",
    randomMode: "랜덤 챌린지",
    oneGuess: "10초 · 한 번의 답",
    drawSomething: "무언가 그리기",
    privacyLine: "무료. 앱도, 계정도 필요 없어요. 링크 하나면 끝.",
    forBrave: "용감한 누군가에게",
    canTheyTell: "알아볼까?",
    oneGuessNoMercy: "한 번뿐. 봐주기 없음.",
    quit: "나가기",
    yourPrompt: "제시어",
    makeRecognizable: "알아볼 수 있게 그려요. 너무 잘 그리면 실격!",
    timerStarts: "첫 선을 그으면 타이머가 시작돼요.",
    seconds: "{n}초",
    clear: "지우기",
    finish: "그림 완성",
    drawAnywhere: "여기에 그려요",
    noDrawing: "안 그렸어? 과감한데.",
    challengeReady: "챌린지 준비 완료!",
    drawingSafe: "짧은 링크는 30일 후 만료돼요. 해당 링크가 작동하도록 공유된 그림은 임시로 저장돼요. 링크가 있는 사람은 누구나 리플레이할 수 있어요. 비밀은 그리지 마세요.",
    shareTitle: "내 그림 참사 보내기",
    shareBody: "친구 한 명에게 도전장을 보내거나, 그룹 채팅에 던져 누가 먼저 알아보는지 보세요.",
    shareChallenge: "챌린지 보내기",
    copyLink: "링크 복사",
    linkCopied: "링크를 복사했어!",
    makingShortLink: "짧은 링크 만드는 중…",
    shortLinkFallback: "짧은 링크 서비스를 사용할 수 없어 더 긴 백업 링크를 복사했어요.",
    someoneDrew: "누군가 이걸 그렸어…",
    guessBeforeFinish: "뭘 그리려고 한 걸까?",
    startGuessing: "리플레이 시작",
    yourGuess: "내 답",
    replay: "다시 보기",
    correct: "정답!",
    wrong: "아깝다!",
    tooSlow: "시간 초과!",
    timeTaken: "걸린 시간",
    itWas: "정답은 {answer}였어요.",
    recognitionTime: "맞히는 시간",
    drawOneBack: "하나 다시 그려주기",
    challengeSomeoneElse: "다른 친구에게 도전!",
    dropInGroup: "그룹에 보내기",
    tryAnother: "다른 제시어",
    simplified: "링크를 짧게 유지하도록 선을 살짝 단순화했어요.",
    invalidLink: "그림이 번져버렸어요.",
    invalidBody: "링크가 불완전하거나 더 새 버전에서 만들어졌어요.",
    goHome: "새 챌린지 만들기",
    language: "언어",
    shareText: "이걸 그리는 데 10초밖에 없었어. 뭔지 알겠는 순간 탭해. 기회는 딱 한 번:",
    shareBackText: "너에게 하나 다시 그려줬어. 답은 한 번:",
    tapToGuess: "알겠는 순간 탭하세요. 기회는 한 번뿐이에요.",
    waiting: "곧 잉크가 움직여요…",
    guessedIn: "{n}초 만에 맞힘",
    drawingLimit: "혼돈은 이 정도면 충분해요. 완성해서 보내요.",
  },
};

type PromptWords = readonly [string, string, string, string];

export type PromptPack = {
  id: number;
  words: Record<Locale, PromptWords>;
};

const pack = (id: number, words: Record<Locale, PromptWords>): PromptPack => ({ id, words });

export const PROMPTS: PromptPack[] = [
  pack(0, { en: ["Apple", "Pear", "Peach", "Plum"], hi: ["सेब", "नाशपाती", "आड़ू", "आलूबुखारा"], es: ["Manzana", "Pera", "Melocotón", "Ciruela"], fr: ["Pomme", "Poire", "Pêche", "Prune"], "pt-BR": ["Maçã", "Pera", "Pêssego", "Ameixa"], de: ["Apfel", "Birne", "Pfirsich", "Pflaume"], ja: ["りんご", "なし", "もも", "すもも"], ko: ["사과", "배", "복숭아", "자두"] }),
  pack(1, { en: ["Cat", "Dog", "Fox", "Rabbit"], hi: ["बिल्ली", "कुत्ता", "लोमड़ी", "खरगोश"], es: ["Gato", "Perro", "Zorro", "Conejo"], fr: ["Chat", "Chien", "Renard", "Lapin"], "pt-BR": ["Gato", "Cachorro", "Raposa", "Coelho"], de: ["Katze", "Hund", "Fuchs", "Kaninchen"], ja: ["ネコ", "イヌ", "キツネ", "ウサギ"], ko: ["고양이", "개", "여우", "토끼"] }),
  pack(2, { en: ["Chair", "Stool", "Bench", "Sofa"], hi: ["कुर्सी", "स्टूल", "बेंच", "सोफ़ा"], es: ["Silla", "Taburete", "Banco", "Sofá"], fr: ["Chaise", "Tabouret", "Banc", "Canapé"], "pt-BR": ["Cadeira", "Banqueta", "Banco", "Sofá"], de: ["Stuhl", "Hocker", "Bank", "Sofa"], ja: ["いす", "スツール", "ベンチ", "ソファ"], ko: ["의자", "스툴", "벤치", "소파"] }),
  pack(3, { en: ["Cup", "Mug", "Glass", "Bowl"], hi: ["कप", "मग", "गिलास", "कटोरा"], es: ["Taza", "Tazón", "Vaso", "Cuenco"], fr: ["Tasse", "Mug", "Verre", "Bol"], "pt-BR": ["Xícara", "Caneca", "Copo", "Tigela"], de: ["Tasse", "Becher", "Glas", "Schüssel"], ja: ["カップ", "マグカップ", "グラス", "ボウル"], ko: ["컵", "머그컵", "유리잔", "그릇"] }),
  pack(4, { en: ["Sun", "Moon", "Star", "Cloud"], hi: ["सूरज", "चाँद", "तारा", "बादल"], es: ["Sol", "Luna", "Estrella", "Nube"], fr: ["Soleil", "Lune", "Étoile", "Nuage"], "pt-BR": ["Sol", "Lua", "Estrela", "Nuvem"], de: ["Sonne", "Mond", "Stern", "Wolke"], ja: ["太陽", "月", "星", "雲"], ko: ["해", "달", "별", "구름"] }),
  pack(5, { en: ["Bicycle", "Scooter", "Motorcycle", "Skateboard"], hi: ["साइकिल", "स्कूटर", "मोटरसाइकिल", "स्केटबोर्ड"], es: ["Bicicleta", "Patinete", "Moto", "Patineta"], fr: ["Vélo", "Trottinette", "Moto", "Skateboard"], "pt-BR": ["Bicicleta", "Patinete", "Moto", "Skate"], de: ["Fahrrad", "Roller", "Motorrad", "Skateboard"], ja: ["自転車", "キックボード", "バイク", "スケートボード"], ko: ["자전거", "킥보드", "오토바이", "스케이트보드"] }),
  pack(6, { en: ["Key", "Lock", "Doorbell", "Handle"], hi: ["चाबी", "ताला", "दरवाज़े की घंटी", "हैंडल"], es: ["Llave", "Candado", "Timbre", "Manija"], fr: ["Clé", "Cadenas", "Sonnette", "Poignée"], "pt-BR": ["Chave", "Cadeado", "Campainha", "Maçaneta"], de: ["Schlüssel", "Schloss", "Türklingel", "Klinke"], ja: ["鍵", "南京錠", "ドアベル", "ドアノブ"], ko: ["열쇠", "자물쇠", "초인종", "문손잡이"] }),
  pack(7, { en: ["Pizza", "Burger", "Sandwich", "Taco"], hi: ["पिज़्ज़ा", "बर्गर", "सैंडविच", "टैको"], es: ["Pizza", "Hamburguesa", "Sándwich", "Taco"], fr: ["Pizza", "Burger", "Sandwich", "Taco"], "pt-BR": ["Pizza", "Hambúrguer", "Sanduíche", "Taco"], de: ["Pizza", "Burger", "Sandwich", "Taco"], ja: ["ピザ", "ハンバーガー", "サンドイッチ", "タコス"], ko: ["피자", "햄버거", "샌드위치", "타코"] }),
  pack(8, { en: ["Umbrella", "Parasol", "Raincoat", "Kite"], hi: ["छाता", "धूपछाता", "रेनकोट", "पतंग"], es: ["Paraguas", "Sombrilla", "Impermeable", "Cometa"], fr: ["Parapluie", "Ombrelle", "Imperméable", "Cerf-volant"], "pt-BR": ["Guarda-chuva", "Sombrinha", "Capa de chuva", "Pipa"], de: ["Regenschirm", "Sonnenschirm", "Regenmantel", "Drachen"], ja: ["かさ", "日傘", "レインコート", "たこ"], ko: ["우산", "양산", "우비", "연"] }),
  pack(9, { en: ["Guitar", "Violin", "Ukulele", "Banjo"], hi: ["गिटार", "वायलिन", "यूकुलेले", "बैंजो"], es: ["Guitarra", "Violín", "Ukelele", "Banjo"], fr: ["Guitare", "Violon", "Ukulélé", "Banjo"], "pt-BR": ["Violão", "Violino", "Ukulele", "Banjo"], de: ["Gitarre", "Violine", "Ukulele", "Banjo"], ja: ["ギター", "バイオリン", "ウクレレ", "バンジョー"], ko: ["기타", "바이올린", "우쿨렐레", "밴조"] }),
  pack(10, { en: ["Tree", "Bush", "Flower", "Cactus"], hi: ["पेड़", "झाड़ी", "फूल", "कैक्टस"], es: ["Árbol", "Arbusto", "Flor", "Cactus"], fr: ["Arbre", "Buisson", "Fleur", "Cactus"], "pt-BR": ["Árvore", "Arbusto", "Flor", "Cacto"], de: ["Baum", "Strauch", "Blume", "Kaktus"], ja: ["木", "低木", "花", "サボテン"], ko: ["나무", "관목", "꽃", "선인장"] }),
  pack(11, { en: ["Camera", "Binoculars", "Microscope", "Telescope"], hi: ["कैमरा", "दूरबीन", "माइक्रोस्कोप", "टेलीस्कोप"], es: ["Cámara", "Prismáticos", "Microscopio", "Telescopio"], fr: ["Appareil photo", "Jumelles", "Microscope", "Télescope"], "pt-BR": ["Câmera", "Binóculos", "Microscópio", "Telescópio"], de: ["Kamera", "Fernglas", "Mikroskop", "Teleskop"], ja: ["カメラ", "双眼鏡", "顕微鏡", "望遠鏡"], ko: ["카메라", "쌍안경", "현미경", "망원경"] }),
];

export const fill = (value: string, variables: Record<string, string | number>) =>
  Object.entries(variables).reduce((result, [key, replacement]) => result.replace(`{${key}}`, String(replacement)), value);

export interface DailyProgress {
  lastCompletedDay: string;
  streak: number;
  bestStreak: number;
}

const DAY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

export function utcDayKey(date = new Date()): string {
  return date.toISOString().slice(0, 10);
}

export function isDayKey(value: string): boolean {
  if (!DAY_PATTERN.test(value)) return false;
  const parsed = new Date(`${value}T00:00:00.000Z`);
  return !Number.isNaN(parsed.valueOf()) && utcDayKey(parsed) === value;
}

export function dailyPromptId(day: string): number {
  if (!isDayKey(day)) throw new Error("Invalid daily key");
  let state = 2166136261;
  for (const character of day) {
    state ^= character.charCodeAt(0);
    state = Math.imul(state, 16777619);
  }
  const pack = PROMPTS[(state >>> 0) % PROMPTS.length];
  return pack.id;
}

export function promptById(id: number) {
  return PROMPTS.find((prompt) => prompt.id === id);
}

export function advanceDailyProgress(previous: DailyProgress | null, day: string): DailyProgress {
  if (!isDayKey(day)) throw new Error("Invalid daily key");
  if (!previous || !isDayKey(previous.lastCompletedDay)) {
    return { lastCompletedDay: day, streak: 1, bestStreak: 1 };
  }
  if (previous.lastCompletedDay === day) return previous;

  const previousTime = Date.parse(`${previous.lastCompletedDay}T00:00:00.000Z`);
  const currentTime = Date.parse(`${day}T00:00:00.000Z`);
  const isNextDay = currentTime - previousTime === 86_400_000;
  const streak = isNextDay ? Math.max(1, previous.streak) + 1 : 1;
  return {
    lastCompletedDay: day,
    streak,
    bestStreak: Math.max(previous.bestStreak || 0, streak),
  };
}

export function detectLocale(value?: string | null): Locale {
  const normalized = (value || "en").toLowerCase();
  if (normalized.startsWith("hi")) return "hi";
  if (normalized.startsWith("es")) return "es";
  if (normalized.startsWith("fr")) return "fr";
  if (normalized.startsWith("pt")) return "pt-BR";
  if (normalized.startsWith("de")) return "de";
  if (normalized.startsWith("ja")) return "ja";
  if (normalized.startsWith("ko")) return "ko";
  return "en";
}

export function shuffledOptions(promptId: number, seed: number): number[] {
  const values = [0, 1, 2, 3];
  let state = (seed ^ ((promptId + 1) * 0x9e3779b1)) >>> 0;
  for (let i = values.length - 1; i > 0; i -= 1) {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    const j = (state >>> 0) % (i + 1);
    [values[i], values[j]] = [values[j], values[i]];
  }
  return values;
}
